import type { Lesson, SalahStep } from './types';

export const lessons: Lesson[] = [
  {
    id: 1,
    title: 'The Shahada (Declaration of Faith)',
    category: 'Pillars of Islam',
    description: 'Understand the meaning and importance of the first pillar of Islam, the declaration of faith.',
  },
  {
    id: 2,
    title: 'Introduction to Salah (Prayer)',
    category: 'Pillars of Islam',
    description: 'Learn the fundamentals of the five daily prayers, their timings, and their significance in a Muslim\'s life.',
  },
  {
    id: 3,
    title: 'Wudu (Ablution)',
    category: 'Prayer Prerequisites',
    description: 'A step-by-step guide to performing Wudu, the ritual purification required before prayer.',
  },
  {
    id: 4,
    title: 'Zakat (Charity)',
    category: 'Pillars of Islam',
    description: 'Discover the concept of Zakat, its rules, and its role in creating a compassionate society.',
  },
  {
    id: 5,
    title: 'Sawm (Fasting in Ramadan)',
    category: 'Pillars of Islam',
    description: 'An overview of the fourth pillar of Islam, the fast of Ramadan, and its spiritual benefits.',
  },
  {
    id: 6,
    title: 'Hajj (Pilgrimage)',
    category: 'Pillars of Islam',
    description: 'Learn about the pilgrimage to Mecca, a once-in-a-lifetime duty for those who are able.',
  },
  {
    id: 7,
    title: 'Introduction to the Quran',
    category: 'Core Beliefs',
    description: 'Explore the holy book of Islam, its structure, and its central message to humanity.',
  },
  {
    id: 8,
    title: 'Prophet Muhammad (Peace Be Upon Him)',
    category: 'Core Beliefs',
    description: 'A brief biography of the final prophet and his role as a guide for all Muslims.',
  },
];

export const salahSteps: SalahStep[] = [
    {
      id: 1,
      name: 'Niyyah (Intention)',
      description: 'Stand facing the Qibla (direction of Kaaba in Mecca) and make your intention to pray. This is done in the heart and not spoken. You can use <a href="https://qiblafinder.withgoogle.com/" target="_blank" rel="noopener noreferrer" class="text-primary hover:underline">tools on the web such as this</a> to find the direction of the Kaaba.',
      arabic: 'النية',
      transliteration: 'An-Niyyah',
      translation: 'The Intention',
      imageUrl: '/salah-guide/niyyah.png',
      audioUrl: '/audio/niyyah.mp3',
    },
    {
      id: 2,
      name: 'Takbir al-Ihram',
      description: 'Raise your hands to your ears (for men) or shoulders (for women) and say "Allahu Akbar" (God is the Greatest).',
      arabic: 'الله أكبر',
      transliteration: 'Allahu Akbar',
      translation: 'Allah is the Greatest',
      imageUrl: 'https://placehold.co/600x400',
      audioUrl: '/audio/takbir.mp3',
    },
    {
      id: 3,
      name: 'Qiyam (Standing)',
      description: 'Place your right hand over your left on your chest. Recite the opening chapter of the Quran, Al-Fatiha, followed by another short chapter or verses.',
      arabic: 'القيام',
      transliteration: 'Al-Qiyam',
      translation: 'The Standing',
      imageUrl: 'https://placehold.co/600x400',
      audioUrl: '/audio/qiyam.mp3',
    },
    {
      id: 4,
      name: 'Ruku (Bowing)',
      description: 'Say "Allahu Akbar" and bow down, placing your hands on your knees. Keep your back straight and say "Subhana Rabbiyal Adhim" three times.',
      arabic: 'سبحان ربي العظيم',
      transliteration: 'Subhana Rabbiyal Adhim',
      translation: 'Glory be to my Lord, the Magnificent',
      imageUrl: 'https://placehold.co/600x400',
      audioUrl: '/audio/ruku.mp3',
    },
    {
      id: 5,
      name: 'I\'tidal (Standing up from Bowing)',
      description: 'Rise from bowing and stand straight, saying "Sami\'Allahu liman hamidah". Then say "Rabbana wa lakal hamd".',
      arabic: 'سمع الله لمن حمده، ربنا ولك الحمد',
      transliteration: 'Sami\'Allahu liman hamidah, Rabbana wa lakal hamd',
      translation: 'Allah hears those who praise Him. Our Lord, and to You is all praise',
      imageUrl: 'https://placehold.co/600x400',
      audioUrl: '/audio/itidal.mp3',
    },
    {
      id: 6,
      name: 'Sujud (Prostration)',
      description: 'Say "Allahu Akbar" and go into prostration. Your forehead, nose, palms, knees, and toes should touch the ground. Say "Subhana Rabbiyal A\'la" three times.',
      arabic: 'سبحان ربي الأعلى',
      transliteration: 'Subhana Rabbiyal A\'la',
      translation: 'Glory be to my Lord, the Most High',
      imageUrl: 'https://placehold.co/600x400',
      audioUrl: '/audio/sujud.mp3',
    },
    {
      id: 7,
      name: 'Jalsa (Sitting between Prostrations)',
      description: 'Say "Allahu Akbar" and sit up from prostration. Sit on your left foot with your right foot upright. Say "Rabbighfir li" twice.',
      arabic: 'رب اغفر لي',
      transliteration: 'Rabbighfir li',
      translation: 'My Lord, forgive me',
      imageUrl: 'https://placehold.co/600x400',
      audioUrl: '/audio/jalsa.mp3',
    },
    {
      id: 8,
      name: 'Second Sujud',
      description: 'Perform a second prostration just like the first one, saying "Allahu Akbar" to go down and reciting "Subhana Rabbiyal A\'la" three times.',
      arabic: 'سبحان ربي الأعلى',
      transliteration: 'Subhana Rabbiyal A\'la',
      translation: 'Glory be to my Lord, the Most High',
      imageUrl: 'https://placehold.co/600x400',
      audioUrl: '/audio/sujud.mp3',
    },
     {
      id: 9,
      name: 'Tashahhud',
      description: 'After the second prostration of the second rak\'ah (and the last rak\'ah), sit for the Tashahhud. Recite the required supplications.',
      arabic: 'التشهد',
      transliteration: 'At-Tashahhud',
      translation: 'The Testimony',
      imageUrl: 'https://placehold.co/600x400',
      audioUrl: '/audio/tashahhud.mp3',
    },
    {
      id: 10,
      name: 'Tasleem (Salam)',
      description: 'To end the prayer, turn your face to the right and say "Assalamu Alaikum wa Rahmatullah", then turn to the left and say the same.',
      arabic: 'السلام عليكم ورحمة الله',
      transliteration: 'Assalamu Alaikum wa Rahmatullah',
      translation: 'Peace and mercy of Allah be upon you',
      imageUrl: 'https://placehold.co/600x400',
      audioUrl: '/audio/tasleem.mp3',
    },
  ];
