import type { SalahStep } from './types';

export const salahSteps: SalahStep[] = [
    {
      id: 1,
      name: 'Niyyah (Intention)',
      description: 'Stand facing the Qibla (direction of Kaaba in Mecca) and make your intention to pray. This is done in the heart and not spoken. You can use <a href="https://qiblafinder.withgoogle.com/" target="_blank" rel="noopener noreferrer" class="text-primary hover:underline">tools on the web such as this</a> to find the direction of the Kaaba.',
      arabic: 'النية',
      transliteration: 'An-Niyyah',
      translation: 'The Intention',
      imageUrl: 'https://placehold.co/600x400',
      audioUrl: '/audio/niyyah.mp3',
    },
    {
      id: 2,
      name: 'Takbir al-Ihram',
      description: 'Raise your hands to your ears (for men) or shoulders (for women) and say "Allahu Akbar" (God is the Greatest).',
      arabic: 'الله أكبر',
      transliteration: 'Allahu Akbar',
      translation: 'Allah is the Greatest',
      imageUrl: 'https://placehold.co/600x400',
      audioUrl: '/audio/takbir.mp3',
    },
    {
      id: 3,
      name: 'Qiyam (Standing)',
      description: 'Place your right hand over your left on your chest. Recite the opening chapter of the Quran, <a href="/quran/al-fatiha" class="text-primary hover:underline">Al-Fatiha</a>, followed by another short chapter or verses, such as <a href="/quran/al-asr" class="text-primary hover:underline">Surah Al-Asr</a>.',
      arabic: 'القيام',
      transliteration: 'Al-Qiyam',
      translation: 'The Standing',
      imageUrl: 'https://placehold.co/600x400',
      audioUrl: '/audio/qiyam.mp3',
    },
    {
      id: 4,
      name: 'Ruku (Bowing)',
      description: 'Say "Allahu Akbar" and bow down, placing your hands on your knees. Keep your back straight and say "Subhana Rabbiyal Adhim" three times.',
      arabic: 'سبحان ربي العظيم',
      transliteration: 'Subhana Rabbiyal Adhim',
      translation: 'Glory be to my Lord, the Magnificent',
      imageUrl: 'https://placehold.co/600x400',
      audioUrl: '/audio/ruku.mp3',
    },
    {
      id: 5,
      name: 'I\'tidal (Standing up from Bowing)',
      description: 'Rise from bowing and stand straight, saying "Sami\'Allahu liman hamidah". Then say "Rabbana wa lakal hamd".',
      arabic: 'سمع الله لمن حمده، ربنا ولك الحمد',
      transliteration: 'Sami\'Allahu liman hamidah, Rabbana wa lakal hamd',
      translation: 'Allah hears those who praise Him. Our Lord, and to You is all praise',
      imageUrl: 'https://placehold.co/600x400',
      audioUrl: '/audio/itidal.mp3',
    },
    {
      id: 6,
      name: 'Sujud (Prostration)',
      description: 'Say "Allahu Akbar" and go into prostration. Your forehead, nose, palms, knees, and toes should touch the ground. Say "Subhana Rabbiyal A\'la" three times.',
      arabic: 'سبحان ربي الأعلى',
      transliteration: 'Subhana Rabbiyal A\'la',
      translation: 'Glory be to my Lord, the Most High',
      imageUrl: 'https://placehold.co/600x400',
      audioUrl: '/audio/sujud.mp3',
    },
    {
      id: 7,
      name: 'Jalsa (Sitting between Prostrations)',
      description: 'Say "Allahu Akbar" and sit up from prostration. Sit on your left foot with your right foot upright. Say "Rabbighfir li" twice.',
      arabic: 'رب اغفر لي',
      transliteration: 'Rabbighfir li',
      translation: 'My Lord, forgive me',
      imageUrl: 'https://placehold.co/600x400',
      audioUrl: '/audio/jalsa.mp3',
    },
    {
      id: 8,
      name: 'Second Sujud',
      description: 'Perform a second prostration just like the first one, saying "Allahu Akbar" to go down and reciting "Subhana Rabbiyal A\'la" three times.',
      arabic: 'سبحان ربي الأعلى',
      transliteration: 'Subhana Rabbiyal A\'la',
      translation: 'Glory be to my Lord, the Most High',
      imageUrl: 'https://placehold.co/600x400',
      audioUrl: '/audio/sujud.mp3',
    },
     {
      id: 9,
      name: 'Tashahhud',
      description: 'When to Recite Tashahhud:<br/>- After the second rakʿah of any ṣalāh: you sit and recite the first Tashahhud, then continue standing for the next rakʿah. You do not give taslīm (salām) yet.<br/>- In the final sitting (whether 2, 3, or 4 rakʿah ṣalāh): you recite the Tashahhud and then the Ṣalāt al-Ibrāhīmiyyah (salutations upon Prophet Ibrahim and his family), then you finish with taslīm.',
      arabic: 'التَّحِيَّاتُ للهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ، السَّلَامُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللهِ وَبَرَكَاتُهُ، السَّلَامُ عَلَيْنَا وَعَلَىٰ عِبَادِ اللهِ الصَّالِحِينَ، أَشْهَدُ أَنْ لاَ إِلٰهَ إِلاَّ اللهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ.',
      transliteration: 'At-taḥiyyātu lillāhi waṣ-ṣalawātu waṭ-ṭayyibāt. As-salāmu ʿalayka ayyuhan-nabiyyu wa raḥmatullāhi wa barakātuh. As-salāmu ʿalaynā wa ʿalā ʿibādillāhiṣ-ṣāliḥīn. Ash-hadu an lā ilāha illā Allāh, wa ash-hadu anna Muḥammadan ʿabduhu wa rasūluh.',
      translation: 'All compliments, prayers, and good things are for Allah. Peace be upon you, O Prophet, and the mercy of Allah and His blessings. Peace be upon us and upon the righteous servants of Allah. I bear witness that there is no god but Allah, and I bear witness that Muhammad is His servant and Messenger.',
      imageUrl: 'https://placehold.co/600x400',
      audioUrl: '/audio/tashahhud.mp3',
    },
    {
      id: 10,
      name: 'Ṣalāt al-Ibrāhīmiyyah',
      description: 'Ṣalāt al-Ibrāhīmiyyah (also called al-ṣalawāt) is recited after the Tashahhud in the final rakʿah of the prayer. <br/><br/> <b>When to Recite:</b><br/>In the last rakʿah, after reciting the Tashahhud. Once you finish Ṣalāt al-Ibrāhīmiyyah, you complete the ṣalāh with taslīm.<br/><br/><b>Example:</b><br/>Fajr (2 rakʿah): Tashahhud → Ṣalāt al-Ibrāhīmiyyah → Taslīm.<br/>Maghrib (3 rakʿah): After 2 rakʿah sit → Tashahhud only → stand for 3rd rakʿah → final sitting: Tashahhud + Ṣalāt al-Ibrāhīmiyyah → Taslīm.',
      arabic: 'اللَّهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ وَعَلَىٰ آلِ مُحَمَّدٍ، كَمَا صَلَّيْتَ عَلَىٰ إِبْرَاهِيمَ وَعَلَىٰ آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ.\nاللَّهُمَّ بَارِكْ عَلَىٰ مُحَمَّدٍ وَعَلَىٰ آلِ مُحَمَّدٍ، كَمَا بَارَكْتَ عَلَىٰ إِبْرَاهِيمَ وَعَلَىٰ آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ.',
      transliteration: 'Allāhumma ṣalli ʿalā Muḥammad, wa ʿalā āli Muḥammad, kamā ṣallayta ʿalā Ibrāhīm, wa ʿalā āli Ibrāhīm, innaka ḥamīdun majīd. \n Allāhumma bārik ʿalā Muḥammad, wa ʿalā āli Muḥammad, kamā bārakta ʿalā Ibrāhīm, wa ʿalā āli Ibrāhīm, innaka ḥamīdun majīd.',
      translation: 'O Allah, send prayers upon Muhammad and the family of Muhammad, as You sent prayers upon Ibrāhīm and the family of Ibrāhīm. Verily, You are Praiseworthy, Glorious. \n O Allah, send blessings upon Muhammad and the family of Muhammad, as You blessed Ibrāhīm and the family of Ibrāhīm. Verily, You are Praiseworthy, Glorious.',
      imageUrl: 'https://placehold.co/600x400',
      audioUrl: '/audio/salat-al-ibrahimiyyah.mp3',
    },
    {
      id: 11,
      name: 'Tasleem (Salam)',
      description: 'To end the prayer, turn your face to the right and say "Assalamu Alaikum wa Rahmatullah", then turn to the left and say the same.',
      arabic: 'السلام عليكم ورحمة الله',
      transliteration: 'Assalamu Alaikum wa Rahmatullah',
      translation: 'Peace and mercy of Allah be upon you',
      imageUrl: 'https://placehold.co/600x400',
      audioUrl: '/audio/tasleem.mp3',
    },
  ];

